### ISSUE TITLE
Language version build errors

### ISSUE THREAD

**Issue by belg4mit** [tsujan/Arqiver#22]
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE -DDATADIR=\"/usr/share\" -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -o main.o main.cpp
In file included from mainWin.h:33:0,
                 from main.cpp:26:
config.h:32:3: warning: identifier ‘nullptr’ is a keyword in C++11 [-Wc++0x-compat]
   Settings(const QString &organization, const QString &application = QString(), QObject *parent = nullptr)
   ^
config.h:32:99: error: ‘nullptr’ was not declared in this scope
   Settings(const QString &organization, const QString &application = QString(), QObject *parent = nullptr)
                                                                                                   ^
In file included from main.cpp:26:0:
mainWin.h:44:48: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [enabled by default]
   bool operator<(const QTreeWidgetItem& other) const override;
                                                ^
mainWin.h:39:44: error: ‘nullptr’ was not declared in this scope
   TreeWidgetItem(QTreeWidgetItem *parent = nullptr, int type = QTreeWidgetItem::Type) :
                                            ^
main.cpp: In function ‘void handleQuitSignals(const std::vector<int, std::allocator<int> >&)’:
main.cpp:29:3: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
   auto handler = [](int sig) ->void {
   ^
main.cpp:29:8: error: ‘handler’ does not name a type
   auto handler = [](int sig) ->void {
        ^
main.cpp:34:17: error: range-based ‘for’ loops are not allowed in C++98 mode
   for(int sig : quitSignals)
                 ^
main.cpp:35:17: error: ‘handler’ was not declared in this scope
     signal(sig, handler);
                 ^
main.cpp: In function ‘int main(int, char**)’:
main.cpp:75:20: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
   handleQuitSignals({SIGQUIT, SIGINT, SIGTERM, SIGHUP});
                    ^
main.cpp:75:55: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
   handleQuitSignals({SIGQUIT, SIGINT, SIGTERM, SIGHUP});
                                                       ^
main.cpp:75:55: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
main.cpp:75:55: error: invalid initialization of reference of type ‘const std::vector<int, std::allocator<int> >&’ from expression of type ‘<brace-enclosed initializer list>’
main.cpp:28:6: warning: in passing argument 1 of ‘void handleQuitSignals(const std::vector<int, std::allocator<int> >&)’ [enabled by default]
 void handleQuitSignals(const std::vector<int>& quitSignals) {
      ^
make: *** [main.o] Error 1

**Comment by tsujan** [comment]
You should have a VERY old system. All Linux distros have c++11.

**Comment by belg4mit** [comment]
You contradict yourself, clearly not all systems have c++11. Nevertheless, my g++ does support -std=c+11 however the install file lists no such prerequisites nor does the Makefile specify such. However, in c++11 mode the code compile:

g++ -std=c++11 -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE -DDATADIR=\"/usr/share\" -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -o mainWin.o mainWin.cpp
In file included from ui_mainWin.h:29:0,
                 from mainWin.cpp:21:
treeWidget.h: In member function ‘QModelIndex Arqiver::TreeWidget::getIndexFromItem(const QTreeWidgetItem*) const’:
treeWidget.h:43:30: error: invalid conversion from ‘const QTreeWidgetItem*’ to ‘QTreeWidgetItem*’ [-fpermissive]
     return indexFromItem(item);
                              ^
In file included from /usr/include/qt5/QtWidgets/QTreeWidgetItem:1:0,
                 from mainWin.h:26,
                 from mainWin.cpp:20:
/usr/include/qt5/QtWidgets/qtreewidget.h:357:17: error:   initializing argument 1 of ‘QModelIndex QTreeWidget::indexFromItem(QTreeWidgetItem*, int) const’ [-fpermissive]
     QModelIndex indexFromItem(QTreeWidgetItem *item, int column = 0) const;
                 ^
mainWin.cpp: In member function ‘void Arqiver::mainWin::loadArguments(const QStringList&)’:
mainWin.cpp:401:4: error: no matching function for call to ‘QTimer::singleShot(int, Arqiver::mainWin* const, Arqiver::mainWin::loadArguments(const QStringList&)::__lambda56)’
   });
    ^
mainWin.cpp:401:4: note: candidates are:
In file included from /usr/include/qt5/QtCore/QTimer:1:0,
                 from label.h:24,
                 from mainWin.h:32,
                 from mainWin.cpp:20:
/usr/include/qt5/QtCore/qtimer.h:81:17: note: static void QTimer::singleShot(int, const QObject*, const char*)
     static void singleShot(int msec, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:81:17: note:   no known conversion for argument 3 from ‘Arqiver::mainWin::loadArguments(const QStringList&)::__lambda56’ to ‘const char*’
/usr/include/qt5/QtCore/qtimer.h:82:17: note: static void QTimer::singleShot(int, Qt::TimerType, const QObject*, const char*)
     static void singleShot(int msec, Qt::TimerType timerType, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:82:17: note:   candidate expects 4 arguments, 3 provided
mainWin.cpp: In member function ‘QString Arqiver::mainWin::filterToExtension(const QString&)’:
mainWin.cpp:552:49: error: no matching function for call to ‘QString::indexOf(const QRegularExpression&, int, QRegularExpressionMatch*)’
     int indx = f.indexOf(archivingExt, 0, &match);
                                                 ^
mainWin.cpp:552:49: note: candidates are:
In file included from /usr/include/qt5/QtCore/qobject.h:49:0,
                 from /usr/include/qt5/QtWidgets/qwidget.h:46,
                 from /usr/include/qt5/QtWidgets/qmainwindow.h:45,
                 from /usr/include/qt5/QtWidgets/QMainWindow:1,
                 from mainWin.h:23,
                 from mainWin.cpp:20:
/usr/include/qt5/QtCore/qstring.h:308:9: note: int QString::indexOf(QChar, int, Qt::CaseSensitivity) const
     int indexOf(QChar c, int from = 0, Qt::CaseSensitivity cs = Qt::CaseSensitive) const;
         ^
/usr/include/qt5/QtCore/qstring.h:308:9: note:   no known conversion for argument 1 from ‘const QRegularExpression’ to ‘QChar’
/usr/include/qt5/QtCore/qstring.h:309:9: note: int QString::indexOf(const QString&, int, Qt::CaseSensitivity) const
     int indexOf(const QString &s, int from = 0, Qt::CaseSensitivity cs = Qt::CaseSensitive) const;
         ^
/usr/include/qt5/QtCore/qstring.h:309:9: note:   no known conversion for argument 1 from ‘const QRegularExpression’ to ‘const QString&’
/usr/include/qt5/QtCore/qstring.h:310:9: note: int QString::indexOf(QLatin1String, int, Qt::CaseSensitivity) const
     int indexOf(QLatin1String s, int from = 0, Qt::CaseSensitivity cs = Qt::CaseSensitive) const;
         ^
/usr/include/qt5/QtCore/qstring.h:310:9: note:   no known conversion for argument 1 from ‘const QRegularExpression’ to ‘QLatin1String’
/usr/include/qt5/QtCore/qstring.h:311:9: note: int QString::indexOf(const QStringRef&, int, Qt::CaseSensitivity) const
     int indexOf(const QStringRef &s, int from = 0, Qt::CaseSensitivity cs = Qt::CaseSensitive) const;
         ^
/usr/include/qt5/QtCore/qstring.h:311:9: note:   no known conversion for argument 1 from ‘const QRegularExpression’ to ‘const QStringRef&’
/usr/include/qt5/QtCore/qstring.h:325:9: note: int QString::indexOf(const QRegExp&, int) const
     int indexOf(const QRegExp &, int from = 0) const;
         ^
/usr/include/qt5/QtCore/qstring.h:325:9: note:   candidate expects 2 arguments, 3 provided
/usr/include/qt5/QtCore/qstring.h:330:9: note: int QString::indexOf(QRegExp&, int) const
     int indexOf(QRegExp &, int from = 0) const;
         ^
/usr/include/qt5/QtCore/qstring.h:330:9: note:   candidate expects 2 arguments, 3 provided
/usr/include/qt5/QtCore/qstring.h:336:9: note: int QString::indexOf(const QRegularExpression&, int) const
     int indexOf(const QRegularExpression &re, int from = 0) const;
         ^
/usr/include/qt5/QtCore/qstring.h:336:9: note:   candidate expects 2 arguments, 3 provided
mainWin.cpp: In member function ‘void Arqiver::mainWin::newArchive()’:
mainWin.cpp:589:57: error: no matching function for call to ‘QString::lastIndexOf(const QRegularExpression&, int, QRegularExpressionMatch*)’
     int indx = file.lastIndexOf(archivingExt, -1, &match);
                                                         ^
mainWin.cpp:589:57: note: candidates are:
In file included from /usr/include/qt5/QtCore/qobject.h:49:0,
                 from /usr/include/qt5/QtWidgets/qwidget.h:46,
                 from /usr/include/qt5/QtWidgets/qmainwindow.h:45,
                 from /usr/include/qt5/QtWidgets/QMainWindow:1,
                 from mainWin.h:23,
                 from mainWin.cpp:20:
/usr/include/qt5/QtCore/qstring.h:312:9: note: int QString::lastIndexOf(QChar, int, Qt::CaseSensitivity) const
     int lastIndexOf(QChar c, int from = -1, Qt::CaseSensitivity cs = Qt::CaseSensitive) const;
         ^
/usr/include/qt5/QtCore/qstring.h:312:9: note:   no known conversion for argument 1 from ‘const QRegularExpression’ to ‘QChar’
/usr/include/qt5/QtCore/qstring.h:313:9: note: int QString::lastIndexOf(const QString&, int, Qt::CaseSensitivity) const
     int lastIndexOf(const QString &s, int from = -1, Qt::CaseSensitivity cs = Qt::CaseSensitive) const;
         ^
/usr/include/qt5/QtCore/qstring.h:313:9: note:   no known conversion for argument 1 from ‘const QRegularExpression’ to ‘const QString&’
/usr/include/qt5/QtCore/qstring.h:314:9: note: int QString::lastIndexOf(QLatin1String, int, Qt::CaseSensitivity) const
     int lastIndexOf(QLatin1String s, int from = -1, Qt::CaseSensitivity cs = Qt::CaseSensitive) const;
         ^
/usr/include/qt5/QtCore/qstring.h:314:9: note:   no known conversion for argument 1 from ‘const QRegularExpression’ to ‘QLatin1String’
/usr/include/qt5/QtCore/qstring.h:315:9: note: int QString::lastIndexOf(const QStringRef&, int, Qt::CaseSensitivity) const
     int lastIndexOf(const QStringRef &s, int from = -1, Qt::CaseSensitivity cs = Qt::CaseSensitive) const;
         ^
/usr/include/qt5/QtCore/qstring.h:315:9: note:   no known conversion for argument 1 from ‘const QRegularExpression’ to ‘const QStringRef&’
/usr/include/qt5/QtCore/qstring.h:326:9: note: int QString::lastIndexOf(const QRegExp&, int) const
     int lastIndexOf(const QRegExp &, int from = -1) const;
         ^
/usr/include/qt5/QtCore/qstring.h:326:9: note:   candidate expects 2 arguments, 3 provided
/usr/include/qt5/QtCore/qstring.h:331:9: note: int QString::lastIndexOf(QRegExp&, int) const
     int lastIndexOf(QRegExp &, int from = -1) const;
         ^
/usr/include/qt5/QtCore/qstring.h:331:9: note:   candidate expects 2 arguments, 3 provided
/usr/include/qt5/QtCore/qstring.h:337:9: note: int QString::lastIndexOf(const QRegularExpression&, int) const
     int lastIndexOf(const QRegularExpression &re, int from = -1) const;
         ^
/usr/include/qt5/QtCore/qstring.h:337:9: note:   candidate expects 2 arguments, 3 provided
mainWin.cpp: In member function ‘void Arqiver::mainWin::addFiles()’:
mainWin.cpp:712:37: error: ‘qAsConst’ was not declared in this scope
     for (auto &file : qAsConst(files)) {
                                     ^
mainWin.cpp: In member function ‘void Arqiver::mainWin::nextAutoExtraction()’:
mainWin.cpp:969:50: error: no matching function for call to ‘QTimer::singleShot(int, Arqiver::mainWin* const, bool (QWidget::*)())’
     QTimer::singleShot(500, this, &QWidget::close);
                                                  ^
mainWin.cpp:969:50: note: candidates are:
In file included from /usr/include/qt5/QtCore/QTimer:1:0,
                 from label.h:24,
                 from mainWin.h:32,
                 from mainWin.cpp:20:
/usr/include/qt5/QtCore/qtimer.h:81:17: note: static void QTimer::singleShot(int, const QObject*, const char*)
     static void singleShot(int msec, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:81:17: note:   no known conversion for argument 3 from ‘bool (QWidget::*)()’ to ‘const char*’
/usr/include/qt5/QtCore/qtimer.h:82:17: note: static void QTimer::singleShot(int, Qt::TimerType, const QObject*, const char*)
     static void singleShot(int msec, Qt::TimerType timerType, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:82:17: note:   candidate expects 4 arguments, 3 provided
mainWin.cpp: In member function ‘void Arqiver::mainWin::extractSelection()’:
mainWin.cpp:1020:45: error: ‘qAsConst’ was not declared in this scope
     for (const auto &file : qAsConst(selList)) {
                                             ^
mainWin.cpp: In member function ‘void Arqiver::mainWin::updateTree()’:
mainWin.cpp:1117:45: error: ‘qAsConst’ was not declared in this scope
   for (const auto& thisFile : qAsConst(files)) {
                                             ^
mainWin.cpp:1225:6: error: no matching function for call to ‘QTimer::singleShot(int, Arqiver::mainWin* const, Arqiver::mainWin::updateTree()::__lambda63)’
     });
      ^
mainWin.cpp:1225:6: note: candidates are:
In file included from /usr/include/qt5/QtCore/QTimer:1:0,
                 from label.h:24,
                 from mainWin.h:32,
                 from mainWin.cpp:20:
/usr/include/qt5/QtCore/qtimer.h:81:17: note: static void QTimer::singleShot(int, const QObject*, const char*)
     static void singleShot(int msec, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:81:17: note:   no known conversion for argument 3 from ‘Arqiver::mainWin::updateTree()::__lambda63’ to ‘const char*’
/usr/include/qt5/QtCore/qtimer.h:82:17: note: static void QTimer::singleShot(int, Qt::TimerType, const QObject*, const char*)
     static void singleShot(int msec, Qt::TimerType timerType, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:82:17: note:   candidate expects 4 arguments, 3 provided
mainWin.cpp:1228:6: error: no matching function for call to ‘QTimer::singleShot(int, Arqiver::mainWin* const, Arqiver::mainWin::updateTree()::__lambda64)’
     });
      ^
mainWin.cpp:1228:6: note: candidates are:
In file included from /usr/include/qt5/QtCore/QTimer:1:0,
                 from label.h:24,
                 from mainWin.h:32,
                 from mainWin.cpp:20:
/usr/include/qt5/QtCore/qtimer.h:81:17: note: static void QTimer::singleShot(int, const QObject*, const char*)
     static void singleShot(int msec, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:81:17: note:   no known conversion for argument 3 from ‘Arqiver::mainWin::updateTree()::__lambda64’ to ‘const char*’
/usr/include/qt5/QtCore/qtimer.h:82:17: note: static void QTimer::singleShot(int, Qt::TimerType, const QObject*, const char*)
     static void singleShot(int msec, Qt::TimerType timerType, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:82:17: note:   candidate expects 4 arguments, 3 provided
mainWin.cpp:1232:8: error: no matching function for call to ‘QTimer::singleShot(int, Arqiver::mainWin* const, Arqiver::mainWin::updateTree()::__lambda65)’
       });
        ^
mainWin.cpp:1232:8: note: candidates are:
In file included from /usr/include/qt5/QtCore/QTimer:1:0,
                 from label.h:24,
                 from mainWin.h:32,
                 from mainWin.cpp:20:
/usr/include/qt5/QtCore/qtimer.h:81:17: note: static void QTimer::singleShot(int, const QObject*, const char*)
     static void singleShot(int msec, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:81:17: note:   no known conversion for argument 3 from ‘Arqiver::mainWin::updateTree()::__lambda65’ to ‘const char*’
/usr/include/qt5/QtCore/qtimer.h:82:17: note: static void QTimer::singleShot(int, Qt::TimerType, const QObject*, const char*)
     static void singleShot(int msec, Qt::TimerType timerType, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:82:17: note:   candidate expects 4 arguments, 3 provided
mainWin.cpp:1238:6: error: no matching function for call to ‘QTimer::singleShot(int, Arqiver::mainWin* const, Arqiver::mainWin::updateTree()::__lambda66)’
     });
      ^
mainWin.cpp:1238:6: note: candidates are:
In file included from /usr/include/qt5/QtCore/QTimer:1:0,
                 from label.h:24,
                 from mainWin.h:32,
                 from mainWin.cpp:20:
/usr/include/qt5/QtCore/qtimer.h:81:17: note: static void QTimer::singleShot(int, const QObject*, const char*)
     static void singleShot(int msec, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:81:17: note:   no known conversion for argument 3 from ‘Arqiver::mainWin::updateTree()::__lambda66’ to ‘const char*’
/usr/include/qt5/QtCore/qtimer.h:82:17: note: static void QTimer::singleShot(int, Qt::TimerType, const QObject*, const char*)
     static void singleShot(int msec, Qt::TimerType timerType, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:82:17: note:   candidate expects 4 arguments, 3 provided
mainWin.cpp:1250:8: error: no matching function for call to ‘QTimer::singleShot(int, Arqiver::mainWin* const, Arqiver::mainWin::updateTree()::__lambda67)’
       });
        ^
mainWin.cpp:1250:8: note: candidates are:
In file included from /usr/include/qt5/QtCore/QTimer:1:0,
                 from label.h:24,
                 from mainWin.h:32,
                 from mainWin.cpp:20:
/usr/include/qt5/QtCore/qtimer.h:81:17: note: static void QTimer::singleShot(int, const QObject*, const char*)
     static void singleShot(int msec, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:81:17: note:   no known conversion for argument 3 from ‘Arqiver::mainWin::updateTree()::__lambda67’ to ‘const char*’
/usr/include/qt5/QtCore/qtimer.h:82:17: note: static void QTimer::singleShot(int, Qt::TimerType, const QObject*, const char*)
     static void singleShot(int msec, Qt::TimerType timerType, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:82:17: note:   candidate expects 4 arguments, 3 provided
mainWin.cpp:1265:4: error: no matching function for call to ‘QTimer::singleShot(int, Arqiver::mainWin* const, Arqiver::mainWin::updateTree()::__lambda68)’
   });
    ^
mainWin.cpp:1265:4: note: candidates are:
In file included from /usr/include/qt5/QtCore/QTimer:1:0,
                 from label.h:24,
                 from mainWin.h:32,
                 from mainWin.cpp:20:
/usr/include/qt5/QtCore/qtimer.h:81:17: note: static void QTimer::singleShot(int, const QObject*, const char*)
     static void singleShot(int msec, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:81:17: note:   no known conversion for argument 3 from ‘Arqiver::mainWin::updateTree()::__lambda68’ to ‘const char*’
/usr/include/qt5/QtCore/qtimer.h:82:17: note: static void QTimer::singleShot(int, Qt::TimerType, const QObject*, const char*)
     static void singleShot(int msec, Qt::TimerType timerType, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:82:17: note:   candidate expects 4 arguments, 3 provided
mainWin.cpp: In member function ‘void Arqiver::mainWin::procFinished(bool, const QString&)’:
mainWin.cpp:1386:50: error: no matching function for call to ‘QTimer::singleShot(int, Arqiver::mainWin* const, bool (QWidget::*)())’
     QTimer::singleShot(500, this, &QWidget::close);
                                                  ^
mainWin.cpp:1386:50: note: candidates are:
In file included from /usr/include/qt5/QtCore/QTimer:1:0,
                 from label.h:24,
                 from mainWin.h:32,
                 from mainWin.cpp:20:
/usr/include/qt5/QtCore/qtimer.h:81:17: note: static void QTimer::singleShot(int, const QObject*, const char*)
     static void singleShot(int msec, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:81:17: note:   no known conversion for argument 3 from ‘bool (QWidget::*)()’ to ‘const char*’
/usr/include/qt5/QtCore/qtimer.h:82:17: note: static void QTimer::singleShot(int, Qt::TimerType, const QObject*, const char*)
     static void singleShot(int msec, Qt::TimerType timerType, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:82:17: note:   candidate expects 4 arguments, 3 provided
mainWin.cpp: In member function ‘void Arqiver::mainWin::stretchFirstColumn(bool)’:
mainWin.cpp:1431:4: error: no matching function for call to ‘QTimer::singleShot(int, Arqiver::mainWin* const, Arqiver::mainWin::stretchFirstColumn(bool)::__lambda69)’
   });
    ^
mainWin.cpp:1431:4: note: candidates are:
In file included from /usr/include/qt5/QtCore/QTimer:1:0,
                 from label.h:24,
                 from mainWin.h:32,
                 from mainWin.cpp:20:
/usr/include/qt5/QtCore/qtimer.h:81:17: note: static void QTimer::singleShot(int, const QObject*, const char*)
     static void singleShot(int msec, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:81:17: note:   no known conversion for argument 3 from ‘Arqiver::mainWin::stretchFirstColumn(bool)::__lambda69’ to ‘const char*’
/usr/include/qt5/QtCore/qtimer.h:82:17: note: static void QTimer::singleShot(int, Qt::TimerType, const QObject*, const char*)
     static void singleShot(int msec, Qt::TimerType timerType, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:82:17: note:   candidate expects 4 arguments, 3 provided
mainWin.cpp:1434:4: error: no matching function for call to ‘QTimer::singleShot(int, Arqiver::mainWin* const, Arqiver::mainWin::stretchFirstColumn(bool)::__lambda70)’
   });
    ^
mainWin.cpp:1434:4: note: candidates are:
In file included from /usr/include/qt5/QtCore/QTimer:1:0,
                 from label.h:24,
                 from mainWin.h:32,
                 from mainWin.cpp:20:
/usr/include/qt5/QtCore/qtimer.h:81:17: note: static void QTimer::singleShot(int, const QObject*, const char*)
     static void singleShot(int msec, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:81:17: note:   no known conversion for argument 3 from ‘Arqiver::mainWin::stretchFirstColumn(bool)::__lambda70’ to ‘const char*’
/usr/include/qt5/QtCore/qtimer.h:82:17: note: static void QTimer::singleShot(int, Qt::TimerType, const QObject*, const char*)
     static void singleShot(int msec, Qt::TimerType timerType, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:82:17: note:   candidate expects 4 arguments, 3 provided
mainWin.cpp:1438:6: error: no matching function for call to ‘QTimer::singleShot(int, Arqiver::mainWin* const, Arqiver::mainWin::stretchFirstColumn(bool)::__lambda71)’
     });
      ^
mainWin.cpp:1438:6: note: candidates are:
In file included from /usr/include/qt5/QtCore/QTimer:1:0,
                 from label.h:24,
                 from mainWin.h:32,
                 from mainWin.cpp:20:
/usr/include/qt5/QtCore/qtimer.h:81:17: note: static void QTimer::singleShot(int, const QObject*, const char*)
     static void singleShot(int msec, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:81:17: note:   no known conversion for argument 3 from ‘Arqiver::mainWin::stretchFirstColumn(bool)::__lambda71’ to ‘const char*’
/usr/include/qt5/QtCore/qtimer.h:82:17: note: static void QTimer::singleShot(int, Qt::TimerType, const QObject*, const char*)
     static void singleShot(int msec, Qt::TimerType timerType, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:82:17: note:   candidate expects 4 arguments, 3 provided
make: *** [mainWin.o] Error 1

**Comment by tsujan** [comment]
You system is EXTREMELY old. All distros support C++11.

**Comment by tsujan** [comment]
> however the install file lists no such prerequisites

Obviously, the file wasn't written for ancient systems.

**Comment by belg4mit** [comment]
No, it obviously was written without consideration for best practices of fully specifying the requirements, or for the build processes to not make assumptions about systems. Nevertheless, even when compiling it in c++11 mode it fails.

**Comment by tsujan** [comment]
No, Your "report" was written without any consideration. You should have mentioned that your system is so unusual and archaic.

> to not make assumptions about systems.

There are always obvious assumptions with git.
