### ISSUE TITLE
Add translations to Weblate

### ISSUE THREAD

**Issue by Vistaus** [tsujan/Arqiver#29]
Hello,

Your other projects are translateble on Weblate. It would be nice if you could add Arqiver as well. 🙂

**Comment by tsujan** [comment]
> Your other projects are translateble on Weblate.

Yes, LXQt team kindly did it.

@stefonarch, is it possible to add Arqiver too? I develop it alongside lxqt-archiver and have ported some of its features to lxqt-archiver.

**Comment by stefonarch** [comment]
Sure, done:
https://translate.lxqt-project.org/projects/tsujan/arqiver/
I think LXQtBot has to clone it to make push work, will do.

**Comment by tsujan** [comment]
Oh, so fast! Thanks a lot!

@Vistaus, thank you too for the suggestion!

**Comment by stefonarch** [comment]
Looks working :)

**Comment by Vistaus** [comment]
Wow, that was fast! Thanks @stefonarch and @tsujan 🙂

**Comment by stefonarch** [comment]
Oh, I forgot: which licence? Atm I inserted "GNU 2.0 and later".

**Comment by tsujan** [comment]
> Oh, I forgot: which licence?

GPL-3.0+ but it isn't important.

**Comment by stefonarch** [comment]
Just one click more today :) done
