### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by hugok79** [tsujan/Arqiver#36]
I can't add the Arqiver portuguese language translation in https://translate.lxqt-project.org/projects/tsujan/arqiver/

I get the following error:

Permission denied error
Insufficient privileges to view this page.

You can add for me @tsujan  ?

**Comment by tsujan** [comment]
@stefonarch 
Should I do something in Weblate to get @hugok79's Portuguese translation?

**Comment by stefonarch** [comment]
Hm, it looks like LXQtBot doesn't create pull requests, or there were no new translations. Somehow hitting "push" it looks like it worked now. There was an issue with GH tokens recently.

**Comment by tsujan** [comment]
Thanks! I didn't touch anything when I logged into Weblate but wasn't sure that I should do something for the PR.

I merged it.

**Comment by hugok79** [comment]
Thanks @tsujan @stefonarch 

Commit: https://github.com/tsujan/Arqiver/pull/37

**Comment by stefonarch** [comment]
Usually there is nothing to do in weblate, or just hitting "commit" and the PR will be created or updated, but this didn't work now, I used "push".

Let's the in future if things  run automatically again.

**Comment by tsujan** [comment]
> Usually there is nothing to do in weblate

I didn't know that. Thanks!

> but this didn't work now, I used "push".

In the last 3-4 days, I saw weird issues in GitHub.
