### ISSUE TITLE
Strange things did happen here...

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/Arqiver#4]
Hello. During a short scratch through the code one of my tools noticed a strange thing:
Expression on line 774 is always true as it was already checked on line 768.
Fixing this requires a deeper analysis on logical stuff. It also possible that everything is okay here. However, I still recommend to check it)
https://github.com/tsujan/Arqiver/blob/a01ce0191bd844d2c4d32c07ee50c5bb3b2cbbc8/backends.cpp#L774

**Comment by tsujan** [comment]
> However, I still recommend to check it

I will. Thanks for telling me!

Whenever I find some free time, I should also fix a bug that I found recently. So, I'll check that line with it.

**Comment by tsujan** [comment]
Ah, at last, I found some time to fix the bug I mentioned before.

As for this page, yes, that expression is always true. It has remained from of a previous code and is harmless. Will remove it later.
