### ISSUE TITLE
Support for Qt4?

### ISSUE THREAD

**Issue by barracuda156** [tsujan/Arqiver#93]
Is it possible to make it build with Qt4?

**Comment by tsujan** [comment]
No; Qt4 is totally dead.

The Qt5 support will be removed after Qt6 becomes the default version in most distros. For now, the app can be compiled against both Qt5 and Qt6.

**Comment by barracuda156** [comment]
Well, Qt5 and Qt6 are hopelessly broken for my platform. Qt4 works perfectly fine.

**Comment by barracuda156** [comment]
@tsujan There was no early version to support Qt4 too, right?

**Comment by tsujan** [comment]
> There was no early version to support Qt4 to

I'm afraid not. Arqiver was started after Qt5 became the default version of Qt in Linux.

**Comment by barracuda156** [comment]
Thank you for a quick reply! Will try to find another option.
